version: 2.0

jobs:
  build:
    # docker:
    #   # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
    #   - image: docker:dind
    machine: true

    steps:
      - checkout
      - run:
          name: build
          command: |
            source ci/prepare.sh
            docker info
            docker_build
            docker_cloud zcong circleci-test prod
workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          context: org-global
          filters:
            tags:
              only: /^v.*/
      # - release:
      #     context: org-global
      #     filters:
      #       tags:
      #         only: /^v.*/
      #       branches:
      #         ignore: /.*/
