version: 2.0

jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: docker:dind

    working_directory: /circleci-test

    steps:
      - checkout
      - run:
          name: prepare ci
          command: source ci/prepare.sh
      - run:
          name: build
          command: |
            - docker info
            - docker_tag_push $CI_BUILD_SHA circleci-test prod

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      # - release:
      #     context: org-global
      #     filters:
      #       tags:
      #         only: /^v.*/
      #       branches:
      #         ignore: /.*/
