version: 2.0

jobs:
  test:
    machine: true
    steps:
      - run: echo no test

  build:
    machine: true
    steps:
      - checkout
      - run:
          name: build
          command: |
            source ci/prepare.sh
            docker info
            docker_build
            mkdir -p docker_cache
            docker save -o docker_cache/docker_built.tar $CIRCLE_PROJECT_REPONAME:$CI_BUILD_SHA
      - save_cache:
          key: docker-build-cache-{{ .Branch }}-{{ .Revision }}
          paths:
            - docker_cache

  deploy:
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: docker-build-cache-{{ .Branch }}-{{ .Revision }}
      - run:
          name: push to production
          command: |
            source ci/prepare.sh
            docker info
            docker load < docker_cache/docker_built.tar
            docker_push zcong circleci-test production

  staging:
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: docker-build-cache-{{ .Branch }}-{{ .Revision }}
      - run:
          name: push to staging
          command: |
            source ci/prepare.sh
            docker info
            docker load < docker_cache/docker_built.tar
            docker_push zcong circleci-test staging

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - build:
          context: org-global
          requires:
            - test
          filters:
            tags:
              only: /.*/
      - staging:
          context: org-global
          requires:
            - build
          filters:
            tags:
              ignore: /^v.*/
      - deploy:
          context: org-global
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
