version: 2.0

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: build
          command: |
            source ci/prepare.sh
            docker info
            docker_build
            mkdir -p docker-cache
            docker save -o docker-cache/built-image.tar $CIRCLE_PROJECT_REPONAME:$CI_BUILD_SHA
      - save_cache:
          key: $CIRCLE_SHA1
          paths:
            - docker-cache

  deploy:
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: $CIRCLE_SHA1
      - run:
          name: push to production
          command: |
            source ci/prepare.sh
            docker info
            docker load < docker-cache/built-image.tar
            docker_push zcong circleci-test production

  staging:
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: $CIRCLE_SHA1
      - run:
          name: push to staging
          command: |
            source ci/prepare.sh
            docker info
            docker load < docker-cache/built-image.tar
            docker_push zcong circleci-test staging


workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          context: org-global
          filters:
            tags:
              only: /^v.*/
      - staging:
          context: org-global
          requires:
            - build
          filters:
            tags:
              ignore: /^v.*/
      - deploy:
          context: org-global
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
