version: 2.0

jobs:
  test:
    machine: true
    steps:
      - run: echo no test

  deploy:
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: $CIRCLE_SHA1
      - run:
          name: push to production
          command: |
            source ci/prepare.sh
            docker info
            docker_build
            docker_push zcong circleci-test production

  staging:
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: $CIRCLE_SHA1
      - run:
          name: push to staging
          command: |
            source ci/prepare.sh
            docker info
            docker_build
            docker_push zcong circleci-test staging


workflows:
  version: 2
  build-n-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - staging:
          context: org-global
          requires:
            - test
          filters:
            tags:
              ignore: /^v.*/
      - deploy:
          context: org-global
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
